`tobit`: Linear Regression for a Left-Censored Dependent Variable {#tobit}
=================================================================

Tobit regression estimates a linear regression model for a left-censored
dependent variable, where the dependent variable is censored from below.
While the classical tobit model has values censored at 0, you may select
another censoring point. For other linear regression models with fully
observed dependent variables, see Bayesian regression (), maximum
likelihood normal regression (), or least squares ().

### Syntax

    > z.out <- zelig(Y ~ X1 + X2, below = 0, above = Inf, 
                      model = "tobit", data = mydata)
    > x.out <- setx(z.out)
    > s.out <- sim(z.out, x = x.out)

### Inputs

<span>zelig()</span> accepts the following arguments to specify how the
dependent variable is censored.

-   `below`: (defaults to 0) The point at which the dependent variable
    is censored from below. If any values in the dependent variable are
    observed to be less than the censoring point, it is assumed that
    that particular observation is censored from below at the observed
    value. (See for a Bayesian implementation that supports both left
    and right censoring.)

-   <span>robust</span>: defaults to <span>FALSE</span>. If
    <span>TRUE</span>, <span>zelig()</span> computes robust standard
    errors based on sandwich estimators (see @Huber81 and @White80) and
    the options selected in <span>cluster</span>.

-   <span>cluster</span>: if <span>robust = TRUE</span>, you may select
    a variable to define groups of correlated observations. Let
    <span>x3</span> be a variable that consists of either discrete
    numeric values, character strings, or factors that define strata.
    Then

        > z.out <- zelig(y ~ x1 + x2, robust = TRUE, cluster = "x3", 
                         model = "tobit", data = mydata)

    means that the observations can be correlated within the strata
    defined by the variable <span>x3</span>, and that robust standard
    errors should be calculated according to those clusters. If
    <span>robust = TRUE</span> but <span>cluster</span> is not
    specified, <span>zelig()</span> assumes that each observation falls
    into its own cluster.

Zelig users may wish to refer to `help(survreg)` for more information.

### Examples

1.  <span>Basic Example</span>\
    Attaching the sample dataset:

    RRR\> data(tobin)

    Estimating linear regression using `tobit`:

    RRR\> z.out \<- zelig(durable   age + quant, model = “tobit”, data =
    tobin)

    Setting values for the explanatory variables to their sample
    averages:

    RRR\> x.out \<- setx(z.out)

    Simulating quantities of interest from the posterior distribution
    given `x.out`.

    RRR\> s.out1 \<- sim(z.out, x = x.out)

    RRR\> summary(s.out1)

2.  <span>Simulating First Differences</span>\
    Set explanatory variables to their default(mean/mode) values, with
    high (80th percentile) and low (20th percentile) liquidity ratio
    (`quant`):

    RRR\> x.high \<- setx(z.out, quant =
    quantile(tobin$quant, prob = 0.8))
    RRR>  x.low <- setx(z.out, quant = quantile(tobin$quant, prob =
    0.2))

    Estimating the first difference for the effect of high versus low
    liquidity ratio on duration(`durable`):

    RRR\> s.out2 \<- sim(z.out, x = x.high, x1 = x.low)

    RRR\> summary(s.out2)

### Model

-   Let $Y_i^*$ be a latent dependent variable which is distributed with
    *stochastic* component

    $$\begin{aligned}
    Y_i^* & \sim & \textrm{Normal}(\mu_i, \sigma^2) \\\end{aligned}$$

    where $\mu_i$ is a vector means and $\sigma^2$ is a scalar variance
    parameter. $Y_i^*$ is not directly observed, however. Rather we
    observed $Y_i$ which is defined as:

    $$Y_i = \left\{
    \begin{array}{lcl}
    Y_i^*  &\textrm{if} & c <Y_i^* \\
    c    &\textrm{if} & c \ge Y_i^* 
    \end{array}\right.$$

    where $c$ is the lower bound below which $Y_i^*$ is censored.

-   The *systematic component* is given by

    $$\begin{aligned}
    \mu_{i} &=& x_{i} \beta,\end{aligned}$$

    where $x_{i}$ is the vector of $k$ explanatory variables for
    observation $i$ and $\beta$ is the vector of coefficients.

### Quantities of Interest

-   The expected values (`qi$ev`) for the tobit regression model are the
    same as the expected value of $Y*$:

    $$E(Y^* | X) = \mu_{i} = x_{i} \beta$$

-   The first difference (`qi$fd`) for the tobit regression model is
    defined as

    $$\begin{aligned}
    \text{FD}=E(Y^* \mid x_{1}) - E(Y^* \mid x).\end{aligned}$$

-   In conditional prediction models, the average expected treatment
    effect (`qi$att.ev`) for the treatment group is

    $$\begin{aligned}
    \frac{1}{\sum t_{i}}\sum_{i:t_{i}=1}[E[Y^*_{i}(t_{i}=1)]-E[Y^*_{i}(t_{i}=0)]],\end{aligned}$$

    where $t_{i}$ is a binary explanatory variable defining the
    treatment ($t_{i}=1$) and control ($t_{i}=0$) groups.

### Output Values

The output of each Zelig command contains useful information which you
may view. For example, if you run:

    z.out <- zelig(y ~ x, model = "tobit.bayes", data)

then you may examine the available information in `z.out` by using
`names(z.out)`, see the draws from the posterior distribution of the
`coefficients` by using `z.out$coefficients`, and view a default summary
of information through `summary(z.out)`. Other elements available
through the `$` operator are listed below.

-   From the `zelig()` output object `z.out`, you may extract:

    -   `coefficients`: draws from the posterior distributions of the
        estimated parameters. The first $k$ columns contain the
        posterior draws of the coefficients $\beta$, and the last column
        contains the posterior draws of the variance $\sigma^2$.

    -   <span>zelig.data</span>: the input data frame if <span>save.data
        = TRUE</span>.

    -   `seed`: the random seed used in the model.

-   From the `sim()` output object `s.out`:

    -   `qi$ev`: the simulated expected value for the specified values
        of `x`.

    -   `qi$fd`: the simulated first difference in the expected values
        given the values specified in `x` and `x1`.

    -   `qi$att.ev`: the simulated average expected treatment effect for
        the treated from conditional prediction models.

How to Cite {#how-to-cite .unnumbered}
-----------

See also {#see-also .unnumbered}
--------

The tobit function is part of the survival library by Terry Therneau,
ported to R by Thomas Lumley. Advanced users may wish to refer to
`help(survfit)` in the survival library and @VenRip02.Sample data are
from @KinAltBur90.
