<span>probit</span>: Probit Regression for Dichotomous Dependent Variables {#probit}
==========================================================================

Use probit regression to model binary dependent variables specified as a
function of a set of explanatory variables.

### Syntax

    > z.out <- zelig(Y ~ X1 + X2, model = "probit", data = mydata)
    > x.out <- setx(z.out)
    > s.out <- sim(z.out, x = x.out, x1 = NULL)

### Additional Inputs

In addition to the standard inputs, <span>zelig()</span> takes the
following additional options for probit regression:

-   <span>robust</span>: defaults to <span>FALSE</span>. If
    <span>TRUE</span> is selected, <span>zelig()</span> computes robust
    standard errors via the <span>sandwich</span> package (see
    @Zeileis04). The default type of robust standard error is
    heteroskedastic and autocorrelation consistent (HAC), and assumes
    that observations are ordered by time index.

    In addition, <span>robust</span> may be a list with the following
    options:

    -   <span>method</span>: Choose from

        -   <span>“vcovHAC”</span>: (default if <span>robust =
            TRUE</span>) HAC standard errors.

        -   <span>“kernHAC”</span>: HAC standard errors using the
            weights given in @Andrews91.

        -   <span>“weave”</span>: HAC standard errors using the weights
            given in @LumHea99.

    -   <span>order.by</span>: defaults to <span>NULL</span> (the
        observations are chronologically ordered as in the original
        data). Optionally, you may specify a vector of weights (either
        as <span>order.by = z</span>, where <span>z</span> exists
        outside the data frame; or as <span>order.by = \~z</span>, where
        <span>z</span> is a variable in the data frame). The
        observations are chronologically ordered by the size of
        <span>z</span>.

    -   <span>…</span>: additional options passed to the functions
        specified in <span>method</span>. See the <span>sandwich</span>
        library and @Zeileis04 for more options.

### Examples

Attach the sample turnout dataset:

\> data(turnout)

Estimate parameter values for the probit regression:

\> z.out \<- zelig(vote   race + educate, model = “probit”, data =
turnout)

\> summary(z.out)

Set values for the explanatory variables to their default values.

\> x.out \<- setx(z.out)

Simulate quantities of interest from the posterior distribution.

\> s.out \<- sim(z.out, x = x.out)

\> summary(s.out)

### Model

Let $Y_i$ be the observed binary dependent variable for observation $i$
which takes the value of either 0 or 1.

-   The *stochastic component* is given by

    $$Y_i \; \sim \; \textrm{Bernoulli}(\pi_i),$$

    where $\pi_i=\Pr(Y_i=1)$.

-   The *systematic component* is

    $$\pi_i \; = \; \Phi (x_i \beta)$$

    where $\Phi(\mu)$ is the cumulative distribution function of the
    Normal distribution with mean 0 and unit variance.

### Quantities of Interest

-   The expected value (<span>qi\$ev</span>) is a simulation of
    predicted probability of success $$E(Y) = \pi_i = \Phi(x_i
      \beta),$$ given a draw of $\beta$ from its sampling distribution.

-   The predicted value (<span>qi\$pr</span>) is a draw from a Bernoulli
    distribution with mean $\pi_i$.

-   The first difference (<span>qi\$fd</span>) in expected values is
    defined as

    $$\textrm{FD} = \Pr(Y = 1 \mid x_1) - \Pr(Y = 1 \mid x).$$

-   The risk ratio (<span>qi\$rr</span>) is defined as

    $$\textrm{RR} = \Pr(Y = 1 \mid x_1) / \Pr(Y = 1 \mid x).$$

-   In conditional prediction models, the average expected treatment
    effect (<span>att.ev</span>) for the treatment group is

    $$\frac{1}{\sum_{i=1}^n t_i}\sum_{i:t_i=1}^n \left\{ Y_i(t_i=1) -
          E[Y_i(t_i=0)] \right\},$$

    where $t_i$ is a binary explanatory variable defining the treatment
    ($t_i=1$) and control ($t_i=0$) groups. Variation in the simulations
    are due to uncertainty in simulating $E[Y_i(t_i=0)]$, the
    counterfactual expected value of $Y_i$ for observations in the
    treatment group, under the assumption that everything stays the same
    except that the treatment indicator is switched to $t_i=0$.

-   In conditional prediction models, the average predicted treatment
    effect (<span>att.pr</span>) for the treatment group is

    $$\frac{1}{\sum_{i=1}^n t_i}\sum_{i:t_i=1}^n \left\{ Y_i(t_i=1) -
          \widehat{Y_i(t_i=0)} \right\},$$

    where $t_i$ is a binary explanatory variable defining the treatment
    ($t_i=1$) and control ($t_i=0$) groups. Variation in the simulations
    are due to uncertainty in simulating $\widehat{Y_i(t_i=0)}$, the
    counterfactual predicted value of $Y_i$ for observations in the
    treatment group, under the assumption that everything stays the same
    except that the treatment indicator is switched to $t_i=0$.

### Output Values

The output of each Zelig command contains useful information which you
may view. For example, if you run
`z.out <- zelig(y ~ x, model = probit, data)`, then you may examine the
available information in `z.out` by using `names(z.out)`, see the
<span>coefficients</span> by using <span>z.out\$coefficients</span>, and
a default summary of information through `summary(z.out)`. Other
elements available through the <span>\$</span> operator are listed
below.

-   From the <span>zelig()</span> output object <span>z.out</span>, you
    may extract:

    -   <span>coefficients</span>: parameter estimates for the
        explanatory variables.

    -   <span>residuals</span>: the working residuals in the final
        iteration of the IWLS fit.

    -   <span>fitted.values</span>: a vector of the in-sample fitted
        values.

    -   <span>linear.predictors</span>: a vector of $x_{i}\beta$.

    -   <span>aic</span>: Akaike’s Information Criterion (minus twice
        the maximized log-likelihood plus twice the number of
        coefficients).

    -   <span>df.residual</span>: the residual degrees of freedom.

    -   <span>df.null</span>: the residual degrees of freedom for the
        null model.

    -   <span>data</span>: the name of the input data frame.

-   From <span>summary(z.out)</span>, you may extract:

    -   <span>coefficients</span>: the parameter estimates with their
        associated standard errors, $p$-values, and $t$-statistics.

    -   <span>cov.scaled</span>: a $k \times k$ matrix of scaled
        covariances.

    -   <span>cov.unscaled</span>: a $k \times k$ matrix of unscaled
        covariances.

-   From the <span>sim()</span> output object <span>s.out</span>, you
    may extract quantities of interest arranged as matrices indexed by
    simulation $\times$ <span>x</span>-observation (for more than one
    <span>x</span>-observation). Available quantities are:

    -   <span>qi\$ev</span>: the simulated expected values, or predicted
        probabilities, for the specified values of <span>x</span>.

    -   <span>qi\$pr</span>: the simulated predicted values drawn from
        the distributions defined by the predicted probabilities.

    -   <span>qi\$fd</span>: the simulated first differences in the
        predicted probabilities for the values specified in
        <span>x</span> and <span>x1</span>.

    -   <span>qi\$rr</span>: the simulated risk ratio for the predicted
        probabilities simulated from <span>x</span> and <span>x1</span>.

    -   <span>qi\$att.ev</span>: the simulated average expected
        treatment effect for the treated from conditional prediction
        models.

    -   <span>qi\$att.pr</span>: the simulated average predicted
        treatment effect for the treated from conditional prediction
        models.

How to Cite the Logit Model {#how-to-cite-the-logit-model .unnumbered}
---------------------------

How to Cite the Zelig Software Package {#how-to-cite-the-zelig-software-package .unnumbered}
--------------------------------------

See also {#see-also .unnumbered}
--------

The probit model is part of the stats package by @VenRip02. Advanced
users may wish to refer to `help(glm)` and `help(family)`, as well as
@McCNel89. Robust standard errors are implemented via the sandwich
package by @Zeileis04. Sample data are from @KinTomWit00.
